python: Include config.h for strlcpy definition
When no definition of strlcpy is found and the local version is used,
compiling python/dnet.c triggers a warning in the preprocessor:

./dnet.c:3649:3: warning: implicit declaration of function ‘strlcpy’;
did you mean ‘strncpy’? [-Wimplicit-function-declaration]

Fix this by including the generated config.h which does define strlcpy.